<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(Version)</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(Version)</FileVersion>
    <RestoreFallbackFolders></RestoreFallbackFolders>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
</Project>
